language: go
sudo: required
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y iputils-ping
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/mattn/gom
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/axw/gocov/gocov
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/mattn/goveralls
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/tools/godep
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/onsi/ginkgo/ginkgo
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/onsi/gomega
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' golang.org/x/crypto/ssh
- go get -a -x -installsuffix cgo -ldflags '-d -s -w' github.com/stretchr/testify/assert
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
after_success:
- sudo apt-get install -y build-essential rubygems libopenssl-ruby ruby-dev rpm
- bundle install
- make AWSnycast
- make dist
- ls -l dist/
- make coverage.out
- $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
go:
- 1.5
- 1.6
env:
- CGO_ENABLED=0 GOOS=linux
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Fsjtv/dMVNDEvrkwxxrZJR1dUf526nG70/SDVfCHKqEBrkTQqPHgymWloo3D9DHpWhBOvbqtRCPLIcy/TqRUCnviZ4HVYlUXER0r7uQXk2eKUoxu6N5DKn/J3BKZwSi3ZW9GicsDqdfhZlnrVweBPzmmcklBqAkBjpfIyynlE+Y=
  file:
    - AWSnycast
    - $(ls dist/awsnycast*.deb)
    - $(ls dist/awsnycast*.rpm)
  on:
    tags: true
